### ISSUE TITLE
Some bugs need to fix

### ISSUE THREAD

**Issue by tuaotuchan** [tuao/some-bugs-need-to-fix#1]
At check out only display one 服务条款, this is not urgent, fix it when you have time.

**Comment by lili0allen** [comment]
2 and 3 has been fixed.
2. Keep open product description in small screen, change 描述 to 产品介绍
3. Display QQ and Wechat icon in small screen for mobile user

**Comment by tuaotuchan** [comment]
Regarding cannot receive emails for QQ mail user, I asked bluehost, here is their reply
"您好，QQ邮箱注册用户收不到邮件，让您的网站技术人员检查下您的网站邮箱设置，看看有什么报错和错误日志来排查。"
I found if I send email from laura@tuaotuchan.com to qq email address, I can receive email, but cannot receive email if user by using qq mail.

**Comment by lili0allen** [comment]
@tuaotuchan 我用QQ邮箱进行注册，我可以收到邮件，只是在垃圾箱里。我觉得问题出现在这封邮件是sent from tuaotuchan@gmail 而不是 xxxx@tuaotuchan.com. 我试图在后台global configuration修改 sent from，但是我收到的邮件依然是tuaotuchan@gmail。你知道怎么修改吗？

**Comment by tuaotuchan** [comment]
有两处邮箱需要修改，你改过global configuration, 另外一处在Virtuemart/Shop/Shopper Information里，我已经改过了。

我测试了一下发现QQ邮箱可以收到激活邮件了。
Fixed issues
4. If user registered by use qq mail, they cannot receive activation email, this link maybe help. If cannot fix the problem, please notify user to avoid use qq mail.

    https://www.linuxbabe.com/mail-server/solve-550-mail-content-denied-error

5. Most registration emails or order emails send to junk folder, please try to find solution.

**Comment by lili0allen** [comment]
嗯 。好了。我用allen@easymode.com.au 和 275739688@qq.com 两个邮箱进行注册，都可以收到邮件，而且不在junk
mail里。

**Comment by lili0allen** [comment]
1. Duplicate cart icon, some words not translated if not refresh the browser.

**Comment by tuaotuchan** [comment]
At check out only display one 服务条款, this is not urgent, fix it when you have time.

**Comment by lili0allen** [comment]
这个多余的服务条款无法找到对应的代码，不知是如何引入的。所以我把另外一个服务条款隐藏了。正好这个被隐藏的服务条款的CheckBox是默认选择的。

**Comment by tuaotuchan** [comment]
好的这样就可以
