### ISSUE TITLE
Website update

### ISSUE THREAD

**Issue by tuaotuchan** [tuao/some-bugs-need-to-fix#2]
我们网站使用的模板，开发商会定期进行升级，请查看附件。你根据情况进行选择升级。如果此更新对咱们网站没有任何帮助，就不用管它。我想听听你的建议，对于之后的任何升级你有什么好的办法即不影响网站的正常运行，还能保证我们的网站总是最新版本。

IMPORTANT! Make a backup before the update!

Version 4.6 ------------------------- 1. Update VM3.2.1 2. Update SP Page builder 3. Update acymailing 4. Update Revslider 5. Fixed Tab products module 6. Fixed Product module 7. Fixed category page 8. Fixed related products 9. Fixed tags and wishlist 10. Fixed frontpage 11. Removed Genius Search 12. Fixed Captcha 13. Fixed sidebar position for mobile devices   What should you do to update
 1. Re-install  \VM2_Flatastic_theme_Joomla3\sources\up_4.6\com_virtuemart.3.2.1_extract_first \VM2_Flatastic_theme_Joomla3\sources\up_4.6\ 
2. Re-upload files from \VM2_Flatastic_theme_Joomla3\sources\up_4.6\re-upload

**Comment by lili0allen** [comment]
Laura, 你还记得你当时安装模板之后，进行了那些代码修改吗？因为如果修改了，再更新模板就会覆盖掉。我看到http://velikorodnov.com/virtuemart/flatastic/index.php/en/women/product-6 这个demo页面并没有duplicate cart icon的问题，不知道是不是因为咱们自己的改动还是模板当初的bug。

**Comment by tuaotuchan** [comment]
我主要修改过css文件，但由于我也安装和卸载过一些插件，可能会受到影响。你能查出问题所在吗？

这也是为什么我担心升级可能会给网站带来麻烦。我的想法是，我们只做必要的升级，升级在线下先测试没有问题后再在线上操作，不知你意下如何？

**Comment by lili0allen** [comment]
我们通常升级的是核心代码，比如Joomla的代码，或者virtuemart的代码。一般情况下，前端模版的代码不应该涉及这些核心代码。只有当我们发现前端有bug（比如duplicate cart icon）时，我们考虑升级模版的相应代码来fix bug。但从这个模版的升级文档中可以看出，它好像涉及到了php代码的修改。

**Comment by tuaotuchan** [comment]
他们不仅更新php, 还会有javascript等等，因为此模板使用了许多外挂插件，所以升级起来会比较麻烦。

**Comment by tuaotuchan** [comment]
Hi Allen, 目前网站的Joomla版本需要升级，还有几个插件，你看一下，必要的请麻烦你升级一下，多谢。

**Comment by tuaotuchan** [comment]
www.laodong.com.au is open now, you can login to check there. Hosting login detail is same as before.
joomla login is same as tuaotuchan.com

**Comment by lili0allen** [comment]
updated joomla to 3.7.0 for both sites.
