### ISSUE TITLE
Discount price change time

### ISSUE THREAD

**Issue by tuaotuchan** [tuao/some-bugs-need-to-fix#3]
Hi Allen, I checked Coles & Woolworth website at 1:00am 19 April 2017, found Coles the discount price already changed, Woolworth not. So I changed Cron Job setting, also I added three new Cron Jobs, please check if there are anything wrong, thanks.

I don't know what's exactly Chemist change the prices, they change every fortnight, this Friday they will change. I set different time to do the Cron job, hope we can find out the changing time.

**Comment by lili0allen** [comment]
Hi Laura, I edited the cron job time of 1006csv, as 1001csv also runs at 0:30.

**Comment by lili0allen** [comment]
close

**Comment by lili0allen** [comment]
close#3

**Comment by tuaotuchan** [comment]
我又上传了好几个csv文件，1007, 1008, 1009，还没设立运行时间。今早五点起我就一直关注Chemist网站的价格，直到现在还没有更改价格，所以具体时间还定不下来，之后我会手动运行代码。等时间定下来后我们再重新设定时间。

我给Chemist打了电话，他们的网站系统可能存在问题，通常不会这样。

**Comment by tuaotuchan** [comment]
今早我查看了一下在我们网站上的Coles产品价格没有改变，说明我们设立的时间过早。我已经将原来的时间延后一小时，并增加一个新的cron job在早晨3点运行。

**Comment by lili0allen** [comment]
ok

2017-05-03 9:12 GMT+10:00 土澳土产 <notifications@github.com>:
