### ISSUE TITLE
服务条款 empty

### ISSUE THREAD

**Issue by lili0allen** [tuao/some-bugs-need-to-fix#5]
please add content to "服务条款"

**Comment by tuaotuchan** [comment]
I notice that, I will add some content there.

**Comment by tuaotuchan** [comment]
我已经添加了服务条款，我发现在check out时出现两处服务条款，我试着取消“Must agree to Terms of Service on EVERY ORDER”，但没有效果。目前我将“One Page Checkout for Virtuemart” plugin的“Checked Terms and condirions”处于选择状态，这样用户就没必要再选择，免去麻烦。

暂时先这样用着，之后有时间你再处理一下，只保留一个服务条款。
