### ISSUE TITLE
下一步计划

### ISSUE THREAD

**Issue by tuaotuchan** [tuao/some-bugs-need-to-fix#6]
目前我已经上传了1928个产品，因为产品数量过多，有些内容可能有误，还有重复和遗漏的产品。暂时大规模上传产品的工作我就先暂时告一段落，不过之后我会在推广过程中不断增加和更新产品。
因为我们的产品的描述只有文字，过于简单，不利于推广刺激销售，之后我会设计产品广告。因为产品量之大，我很难在短时间内完成此任务，所以我就每天设计两到三个广告。我本想去使用[别人的设计](http://www.aomai.com.au/p-364-SWI013.html)，但担心侵权惹上麻烦，所以决定自己设计，但以重点热销产品为主。
广告推广：每周二和每两个周四我会设计广告，然后次日进行广告分发。
网站的推广：我会以各种途径来推广网站，最大限度让客户在网上下定单，等定单不断上升，我们就要考虑开发在线付款的功能，你现在有时间就可以研究一下如何添加付款功能，主要包括：微信付款、支付宝、国内信用卡付款。

**Comment by lili0allen** [comment]
好的。我们原来的laodong那个domain还能用吗？或者我们给tuaotuchan创建一个subdomain。比如 test.tuaotuchan.com 用来作为我们的test environment。这样我们就可以大胆的进行网站升级和代码修改而不影响production的正常运行。

**Comment by tuaotuchan** [comment]
好的, 明天我将域名再转回去, 然候作为我们的测试网站。

On 26 Apr 2017 1:07 pm, "lili0allen" <notifications@github.com> wrote:

好的。我们原来的laodong那个domain还能用吗？或者我们给tuaotuchan创建一个subdomain。比如
test.tuaotuchan.com 用来作为我们的test environment。这样我们就可以大胆的进行网站升级和代码修改而不影响produ
ction的正常运行。

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tuao/some-bugs-need-to-fix/issues/6#issuecomment-297224841>,
or mute the thread

**Comment by tuaotuchan** [comment]
谢谢你的努力，还有几个小问题需要处理，例如在网站上加上exchange rate和如果客户购买商品重量低于1kg提示继续购买。但现在网站还没有推广起来，我不想给你太多的工作量，所以目前任何非急需解决的就暂缓处理。如果你有什么关于网站推广的建议，请一定要知无不言，言无不尽。
